package server

// Exact code-default help only. Keys, enum values, examples and runtime schemas
// are deliberately not translated. This dictionary is used on HTTP copies.
var koreanSchemaDescriptions = map[string]string{
	`Bundle ID（app 类型可选）`:                              `Bundle ID(app 유형에서 선택 사항)`,
	`DNS 解析值列表（subdomain 可选，如 ["1.2.3.4","2.3.4.5"]）`:  `DNS 조회 값 목록(subdomain에서 선택 사항, 예: ["1.2.3.4","2.3.4.5"])`,
	`DNS 解析类型：A/AAAA/CNAME/MX 等（subdomain 可选）`:         `DNS 레코드 유형: A/AAAA/CNAME/MX 등(subdomain에서 선택 사항)`,
	`DSL 查询表达式（语法/字段见工具描述）。未传 id/ids 时必须非空。`:           `DSL 검색식(문법/필드는 도구 설명 참조). id/ids를 전달하지 않으면 필수입니다.`,
	`HTTP 响应体字节数（可选）`:                                  `HTTP 응답 본문 바이트 수(선택 사항)`,
	`HTTP 响应状态码，如 200/301/403/404（可选）`:                 `HTTP 응답 상태 코드, 예: 200/301/403/404(선택 사항)`,
	`HTTP 方法：GET/POST/PUT/PATCH/DELETE 等（endpoint 必填）`: `HTTP 메서드: GET/POST/PUT/PATCH/DELETE 등(endpoint에서 필수)`,
	`ICP 备案号（可选）`:                                      `ICP 등록 번호(선택 사항)`,
	`IP 地址，必须是 IPv4/IPv6 地址，不能填主机名（主机名请用 type=subdomain 的 domain 字段）；ip 类型必填；service/endpoint 类型可填，用于关联 IP`: `IP 주소는 IPv4/IPv6여야 하며 호스트 이름은 사용할 수 없습니다(호스트 이름은 type=subdomain의 domain 필드 사용). ip 유형에서 필수이며 service/endpoint에서는 IP 연결을 위해 선택적으로 입력합니다.`,
	`MCP 服务器名`:          `MCP 서버 이름`,
	`Markdown 正文说明(可选)`: `Markdown 본문 설명(선택 사항)`,
	`Markdown：本次实际步骤、观察、对照、结论依据；无法确认则列出已检查内容和阻塞原因`:                       `Markdown: 실제 수행 단계, 관찰, 대조 및 결론의 근거. 확인할 수 없으면 점검한 내용과 차단 원인을 나열합니다.`,
	`URL 子串过滤（可选，如 'api' / 'login'）`:                                     `URL 부분 문자열 필터(선택 사항, 예: 'api' / 'login')`,
	`[单条] allow(允许)或 deny(禁止);缺省按 deny 处理`:                               `[단일 항목] allow(허용) 또는 deny(금지). 생략 시 deny로 처리합니다.`,
	`[单条] company / root_domain / subdomain / ip / cidr / icp / keyword`: `[단일 항목] company / root_domain / subdomain / ip / cidr / icp / keyword`,
	`[单条] 一个独立可验证的最终目标`:                                                  `[단일 항목] 독립적으로 검증할 수 있는 최종 목표`,
	`[单条] 一句话描述这个探索方向：做什么+为什么。已写清方向即可，不依赖资产 id。`:                         `[단일 항목] 수행할 내용과 이유를 한 문장으로 설명합니다. 방향이 명확하면 충분하며 자산 id에 의존하지 않습니다.`,
	`[单条] 一条操作约束的内容`:                                                     `[단일 항목] 작업 제약 하나의 내용`,
	`[单条] 公司名或id / 域名 / IP / CIDR / ICP / 关键词`:                           `[단일 항목] 기업 이름 또는 id / 도메인 / IP / CIDR / ICP / 키워드`,
	`[单条] 对应漏洞类(若明确),如 SQLi/IDOR;业务逻辑目标可留空`:                              `[단일 항목] 알려진 취약점 분류, 예: SQLi/IDOR. 비즈니스 로직 목표는 비워도 됩니다.`,
	`[单条] 提示内容`:                                        `[단일 항목] 힌트 내용`,
	`[单条] 提示内容，如'重点挖认证后接口'`:                            `[단일 항목] 힌트 내용, 예: '重点挖认证后接口'`,
	`baseline / proof / verification / supporting`:     `역할: baseline / proof / verification / supporting`,
	`critical|high|medium|low`:                         `심각도: critical|high|medium|low`,
	`digest 节点 id（来自概览 cold_digests）`:                  `digest 노드 id(개요의 cold_digests에서 확인)`,
	`favicon MMH3 哈希（可选）`:                              `favicon MMH3 해시(선택 사항)`,
	`get_finding_traffic 返回的证据 version；用于防止报告覆盖新的证据变更`: `get_finding_traffic이 반환한 증거 version. 새로운 증거 변경을 보고서가 덮어쓰지 않도록 합니다.`,
	`http/sse 的 URL`:                                   `http/sse의 URL 주소`,
	`http: 跳过 TLS 证书校验(自签证书时置 true, 默认 false)`:         `http: TLS 인증서 검증 생략(자체 서명 인증서는 true, 기본 false)`,
	`observed（输出里直接看到）| inferred（据现象推断）。否定结论务必如实标注。`: `observed(출력에서 직접 확인) | inferred(현상에서 추론). 부정적 결론도 정확히 표시하세요.`,
	`request 或 response，默认 response`: `request 또는 response, 기본 response`,
	`shell | command | script(仅Python) | http。shell=bash 环境声明(仅告知模型该工具可在 bash 中直接调用，无需 exec/schema)；其余三种需提供 exec`: `shell | command | script(Python 전용) | http. shell은 bash 환경 선언이며 모델에 bash에서 직접 호출 가능함만 알립니다(exec/schema 불필요). 나머지 세 유형은 exec가 필요합니다.`,
	`skill 名`: `스킬 이름`,
	`skill 名(小写字母开头，字母/数字/连字符)`: `스킬 이름(소문자로 시작, 문자/숫자/하이픈)`,
	`skill 描述(必填，说明它做什么/何时用)`:   `스킬 설명(필수, 기능과 사용 시점 설명)`,
	`stdio | http / sse`:                        `연결 유형: stdio | http / sse`,
	`stdio 的启动命令(如 npx)`:                        `stdio 실행 명령(예: npx)`,
	`traffic_get 中 @blob sha256: 后面的 64 位十六进制值`: `traffic_get의 @blob sha256: 뒤에 있는 64자리 16진수 값`,
	`traffic_search 返回的 id`:                     `traffic_search가 반환한 id`,
	`traffic_search 返回的真实流量 ID`:                 `traffic_search가 반환한 실제 트래픽 ID`,
	`【一行】关键证据：命令 + 最能证明结论的那一两行输出。务必简洁，不要粘大段输出（细节放 detail）。`:                                                                                                                             `[한 줄] 핵심 증거: 명령과 결론을 가장 잘 입증하는 출력 한두 줄. 긴 출력은 붙이지 말고 세부 내용은 detail에 작성하세요.`,
	`【优先用这个】提示数组，每个元素字段同顶层（text/asset_ids/traffic_refs）。`:                                                                                                                               `[권장] 힌트 배열. 각 요소는 최상위와 같은 필드(text/asset_ids/traffic_refs)를 사용합니다.`,
	`【优先用这个】要新增的探索方向数组，按顺序处理。每个元素字段同下方顶层字段（summary/asset_ids/parent_ids/priority）。返回 ids 与本数组等长、同序。`:                                                                                    `[권장] 추가할 탐색 방향 배열을 순서대로 처리합니다. 각 요소는 최상위 필드(summary/asset_ids/parent_ids/priority)를 사용하며 반환 ids는 같은 길이와 순서입니다.`,
	`【优先用这个】要新增的提示数组，按顺序处理。每个元素字段同下方顶层字段（text/asset_ids/traffic_refs）。返回 ids 与本数组等长、同序。`:                                                                                                `[권장] 추가할 힌트 배열을 순서대로 처리합니다. 각 요소는 최상위 필드(text/asset_ids/traffic_refs)를 사용하며 반환 ids는 같은 길이와 순서입니다.`,
	`【优先用这个】要新增的目标数组,按顺序处理。每个元素:text(必填,一个独立可验证的最终目标)+ vulnclass(可选)。返回 ids 与本数组等长、同序。`:                                                                                                 `[권장] 추가할 목표 배열을 순서대로 처리합니다. 각 요소는 text(필수, 독립적으로 검증 가능한 최종 목표)와 vulnclass(선택 사항)이며 반환 ids는 같은 길이와 순서입니다.`,
	`【优先用这个】要新增的约束数组,按顺序处理。每个元素:text(必填,一条约束)+ type(allow|deny)。返回 ids 与本数组等长、同序。`:                                                                                                      `[권장] 추가할 제약 배열을 순서대로 처리합니다. 각 요소는 text(필수, 제약 하나)와 type(allow|deny)이며 반환 ids는 같은 길이와 순서입니다.`,
	`【有多条不同结论时用】事实数组，元素字段同下方顶层字段（summary/detail/evidence/confidence/intent_id/asset_ids）；省略 intent_id 则用顶层 intent_id。返回 ids 与本数组等长、同序。`:                                                 `[서로 다른 결론이 여러 개일 때] 사실 배열. 각 요소는 최상위 필드(summary/detail/evidence/confidence/intent_id/asset_ids)를 사용합니다. intent_id 생략 시 최상위 값을 사용하며 반환 ids는 같은 길이와 순서입니다.`,
	`上游锚点 id（可选，0/1/多个）：本方向由哪些【已确认的事实(fact)/发现(finding)】综合得出。**只能填已存在的 fact/finding 节点 id,不能填意图/目标/提示**——意图必须锚在已确认知识上,发现驱动而非凭空规划。多个事实共同产生一个新意图就传多个;顶层全新侦察方向请留空（会自动挂到任务起点 origin fact）。`: `상위 연결 id(선택 사항, 0/1/여러 개): 이 방향의 근거가 된 확인된 fact/finding입니다. 기존 fact/finding 노드 id만 입력하며 실행 계획/목표/힌트는 사용할 수 없습니다. 계획은 확인된 지식과 발견에 기반해야 합니다. 여러 사실에서 도출되면 모두 입력하고, 새로운 최상위 정찰 방향은 비워 두세요(origin fact에 자동 연결).`,
	`为什么这个证据满足该目标`:                  `이 증거가 목표를 충족하는 이유`,
	`产生本事实的意图 id（你领到的意图；批量时作为各条默认）`: `이 사실을 생성한 실행 계획 id(배정받은 계획, 일괄 처리 시 각 항목의 기본값)`,
	`任务 id`:        `작업 id`,
	`任务描述(简短标题)`:   `작업 설명(짧은 제목)`,
	`任务目标(要达成什么)`:  `작업 목표(달성할 결과)`,
	`优先级 0-10，默认5`: `우선순위 0-10, 기본 5`,
	`公司名(不存在则新建、存在则复用；名称唯一)`:                                          `기업 이름(없으면 생성, 있으면 재사용. 이름은 고유함)`,
	`公司图标 URL(可选；仅新建公司时生效)`:                                           `기업 아이콘 URL(선택 사항, 새 기업 생성 시에만 적용)`,
	`关键字（在所有 work 步骤的摘要+完整输出里搜）`:                                      `키워드(모든 work 단계의 요약과 전체 출력 검색)`,
	`关键字：只返回摘要/完整输出命中它的步骤（可选；与 step_ids 互斥）`:                          `키워드: 요약/전체 출력에서 일치하는 단계만 반환(선택 사항, step_ids와 함께 사용 불가)`,
	`分页偏移，默认 0（可选）`:                                                   `페이지 오프셋, 기본 0(선택 사항)`,
	`分页游标：只返回 id 小于该值的更旧事实；省略或 0 = 最新一页`:                              `페이지 커서: 이 값보다 작은 id의 이전 사실만 반환. 생략 또는 0은 최신 페이지`,
	`加入依据(用于审计)，务必填写`:                                                 `추가 근거(감사용), 반드시 입력하세요`,
	`参数 JSON-Schema(shell/command/script 可留空; http 必填且需含 properties)`: `매개변수 JSON-Schema(shell/command/script는 비워도 됨. http는 필수이며 properties 포함)`,
	`发现摘要`: `발견 사항 요약`,
	`发现的认证信息列表，每条含 type/username/password 等字段（可选，追加不覆盖）`: `발견한 인증 정보 목록, 각 항목에 type/username/password 등 포함(선택 사항, 덮어쓰지 않고 추가)`,
	`发给模型的描述`:  `모델에 전달할 설명`,
	`受影响资产 id`: `영향받는 자산 id`,
	`可选：planner 心跳触发间隔(秒)。距上轮规划结束/任务开始满该值且期间无触发 → 触发一轮规划(兜底死锁 + 唤醒去监督飞行中的 worker)。留空或 0 = 默认 600(10min)；`: `선택 사항: planner 하트비트 간격(초). 이전 계획 종료/작업 시작 후 이 시간 동안 다른 트리거가 없으면 계획을 실행합니다(교착 방지 및 실행 중인 worker 감독). 빈 값 또는 0은 기본 600(10min).`,
	`可选：任务级超时(秒)。到点后触发优雅收尾并进入 timeout 终态；留空或 0 = 不限时`:                                                     `선택 사항: 작업 제한 시간(초). 초과 시 정상 마무리 후 timeout 상태로 종료합니다. 빈 값 또는 0은 무제한`,
	`可选：只读继承的来源任务 id 列表(最多 8 个)。子任务可只读引用这些任务已探明的资产/结论作为起点；与 parent_ref 的纯父子指针不同，这是内容继承。`:                  `선택 사항: 읽기 전용으로 상속할 원본 작업 id 목록(최대 8개). 하위 작업은 해당 작업의 자산/결론을 출발점으로 참조합니다. 단순 부모 연결인 parent_ref와 달리 내용을 상속합니다.`,
	`可选：对于简单任务可开启，创建时直接下发一条种子意图(内容=描述+目标)让 worker 免等首轮 planner 直接开跑测试；默认 false(走标准先规划再执行)。`:               `선택 사항: 간단한 작업에서는 생성 시 초기 실행 계획(설명+목표)을 전달하여 worker가 첫 planner를 기다리지 않고 시작합니다. 기본 false(계획 후 실행).`,
	`可选：已核实且对应本提示中具体漏洞的流量引用，保留顺序；交接后 report_finding 可传 evidence_hint_id 携带这些引用。`:                          `선택 사항: 이 힌트의 특정 취약점에 해당하는 검증된 트래픽 참조(순서 유지). 인계 후 report_finding에서 evidence_hint_id로 참조를 전달할 수 있습니다.`,
	`可选：指定本子任务 planner/worker 用的 LLM 配置 id(见 list_llm_profiles)；留空则继承父任务、再回退全局激活配置`:                       `선택 사항: 하위 작업 planner/worker의 LLM 설정 id(list_llm_profiles 참조). 비우면 부모 작업을 상속하고, 없으면 전역 활성 설정 사용`,
	`可选：本任务中对应此漏洞的提示节点 ID，自动携带其结构化 traffic_refs；不能引用继承提示或其他漏洞的提示`:                                         `선택 사항: 이 작업에서 해당 취약점에 대응하는 힌트 노드 ID. 구조화된 traffic_refs를 자동 전달하며 상속된 힌트나 다른 취약점 힌트는 참조할 수 없습니다.`,
	`可选：父任务 id(做父子关联)`: `선택 사항: 부모 작업 id(부모-자식 연결)`,
	`可选：要取完整内容的步骤 id(一次最多 5 个,多传只返回前 5 个,其余在 omitted_step_ids 里列出)`: `선택 사항: 전체 내용을 읽을 단계 id(한 번에 최대 5개, 초과 시 처음 5개만 반환하고 나머지는 omitted_step_ids에 표시)`,
	`可选；HTTP/HTTPS 漏洞先检索并逐条核实请求/响应确实支持漏洞结论，再按复现顺序填写真实 ID。TCP 等非 HTTP 漏洞、未采集或找不到确切记录时省略或传 []，不阻止上报；可在 evidence 说明原因并提供其他可验证证据。不要猜测 ID、按域名/时间推定关联或仅为补包重复探测。用途 baseline 正常对照 / proof 漏洞证明 / verification 补充验证 / supporting 辅助证据。`: `선택 사항: HTTP/HTTPS 취약점은 요청/응답이 결론을 뒷받침하는지 각각 검증한 뒤 재현 순서대로 실제 ID를 입력합니다. 비HTTP 취약점, 미수집 또는 정확한 기록이 없으면 생략하거나 []를 전달해도 보고할 수 있습니다. evidence에 이유와 다른 검증 가능한 증거를 작성하세요. ID 추측, 도메인/시간만으로 연결 추정, 패킷 보충만을 위한 재탐색은 금지합니다. baseline 정상 대조 / proof 취약점 입증 / verification 추가 검증 / supporting 보조 증거.`,
	`命令参数数组`: `명령 인수 배열`,
	`完整 URL，含协议和端口（HTTP 服务必填；service_type 自动设为 http）`: `프로토콜과 포트를 포함한 전체 URL(HTTP 서비스 필수, service_type은 http로 자동 설정)`,
	`对本次探索结论的【总结性一句话】（是对 detail 的概括）`:                 `이번 탐색 결론을 요약하는 한 문장(detail의 요약)`,
	`工具 key(小写字母开头，字母/数字/下划线)`:                        `도구 key(소문자로 시작, 문자/숫자/밑줄)`,
	`应用 ICP 备案（可选）`:                                   `앱 ICP 등록 정보(선택 사항)`,
	`应用分类（可选）`:                                        `앱 분류(선택 사항)`,
	`应用名称（app 类型必填）`:                                  `앱 이름(app 유형 필수)`,
	`应用描述（可选）`:                                        `앱 설명(선택 사항)`,
	`开放端口列表（ip 类型可选）`:                                 `열린 포트 목록(ip 유형 선택 사항)`,
	`归属企业 id（app 类型可选；app 无法靠 scope 自动归因，需显式指定。id 由 add_company_scope 返回）`: `소속 기업 id(app 유형 선택 사항. app은 scope로 자동 연결되지 않아 명시적으로 지정해야 합니다. id는 add_company_scope가 반환)`,
	`归属依据(证据/来源)，务必填写`:  `소속 근거(증거/출처), 반드시 입력하세요`,
	`当前任务的意图 id`:        `현재 작업의 실행 계획 id`,
	`意图 id(该任务里的 work)`: `실행 계획 id(해당 작업의 work)`,
	`意图 id（= work 句柄）`:  `실행 계획 id(= work 핸들)`,
	`执行规格(shell 类型不需要): command→{command}; script→{code}; http→{method,url,headers,body,proxy,use_recording_proxy}`: `실행 규격(shell 유형 불필요): command→{command}; script→{code}; http→{method,url,headers,body,proxy,use_recording_proxy}`,
	`批量：[{kind, value}]。kind∈company/root_domain/subdomain/ip/cidr/icp/keyword。`:                                    `일괄 입력: [{kind, value}]. kind∈company/root_domain/subdomain/ip/cidr/icp/keyword.`,
	`指纹/技术栈列表，如 ["Nginx","Vue","Bootstrap"]（可选）`:                                                                    `핑거프린트/기술 스택 목록, 예: ["Nginx","Vue","Bootstrap"](선택 사항)`,
	`按主机过滤（必填；如 '107.172.96.177'、'107.172.96.177:8082' 或 'http://107.172.96.177:8082/path'）`:                        `호스트 필터(필수, 예: '107.172.96.177', '107.172.96.177:8082' 또는 'http://107.172.96.177:8082/path')`,
	`按事实摘要关键词过滤（不区分大小写）；省略 = 不过滤`:                                                                                   `사실 요약 키워드 필터(대소문자 구분 없음). 생략 시 필터 없음`,
	`按公司名模糊过滤(可选，不区分大小写)；留空返回全部`:                                                                                    `기업 이름 부분 검색(선택 사항, 대소문자 구분 없음). 비우면 전체 반환`,
	`探索图节点 id(非资产 id)`: `탐색 그래프 노드 id(자산 id 아님)`,
	`提示内容`:             `힌트 내용`,
	`搜索关键字`:            `검색 키워드`,
	`摘要流/检索的返回上限（可选）`:  `요약/검색 결과 반환 한도(선택 사항)`,
	`文件完整内容`:           `파일 전체 내용`,
	`是否启用(默认 true)`:    `활성화 여부(기본 true)`,
	`是否延迟(shell 类型无效；仅 command/script/http 的不常用工具才开)`: `지연 로딩 여부(shell에는 적용되지 않음. 자주 쓰지 않는 command/script/http 도구만 활성화)`,
	`服务名称，如 http/ssh/mysql 等（可选）`:                     `서비스 이름, 예: http/ssh/mysql 등(선택 사항)`,
	`服务名称，如 ssh/mysql/redis（service 非 HTTP 时必填）`:      `서비스 이름, 예: ssh/mysql/redis(비HTTP service 필수)`,
	`本事实的相关细节：把这次探索的多个观察事实都写进这里`:                      `이 사실의 세부 내용: 이번 탐색에서 관찰한 여러 사실을 모두 기록합니다.`,
	`本方向要测试/攻击的【目标资产 id】（**尽量传**，0/1/多个；是 list_assets 返回的资产 id，不是探索节点 id）：这条探索方向针对哪些资产（站点/接口/参数/主机等）。只要方向围绕某些具体资产就务必传上——它是「这条探索打哪些目标」的结构化标记，用于覆盖去重、把意图连入资产链路。仅当纯全局侦察、确实没有具体目标资产时才留空。`: `이 방향에서 테스트할 대상 자산 id(가능하면 입력, 0/1/여러 개). list_assets의 자산 id이며 탐색 노드 id가 아닙니다. 사이트/인터페이스/매개변수/호스트 등 특정 자산이 대상이면 반드시 전달하세요. 검증 범위 중복 제거 및 계획-자산 연결에 사용합니다. 구체적인 대상이 없는 전역 정찰만 비워 두세요.`,
	`本次复测结论摘要`:                          `이번 재검증 결론 요약`,
	`本次读取字节数，默认且最大 8192`:                `이번에 읽을 바이트 수, 기본 및 최대 8192`,
	`根域名或子域名（root_domain/subdomain 必填）`: `루트 도메인 또는 하위 도메인(root_domain/subdomain 필수)`,
	`正文全文搜索（可选，至少 3 个字符），匹配请求/响应的头与正文，如 'password' / 'root:x:0' / '内网测试'`: `본문 전문 검색(선택 사항, 최소 3자). 요청/응답 헤더와 본문 검색, 예: 'password' / 'root:x:0' / '内网测试'`,
	`每页数量（默认 10）`:       `페이지당 개수(기본 10)`,
	`每页条数，默认 3，最大 10`:   `페이지당 개수, 기본 3, 최대 10`,
	`清单里的绑定 ID，省略则返回清单`: `목록의 연결 ID, 생략 시 목록 반환`,
	`漏洞名称`:      `취약점 이름`,
	`漏洞类别`:      `취약점 분류`,
	`独立漏洞记录 ID`: `독립 취약점 기록 ID`,
	`独立漏洞记录 ID，从 list_task_findings / get_task_node_detail 的 finding_id 字段读取`: `독립 취약점 기록 ID, list_task_findings / get_task_node_detail의 finding_id 필드에서 확인`,
	`环境变量 {KEY:VALUE}`:                      `환경 변수 {KEY:VALUE}`,
	`目标漏洞 id(report_finding 返回的 id)`:        `대상 취약점 id(report_finding이 반환한 id)`,
	`目标节点 id`:                               `목표 노드 id`,
	`直接按单个资产 id 取（可选，与 dsl/type 互斥）`:        `단일 자산 id로 조회(선택 사항, dsl/type과 함께 사용 불가)`,
	`直接按多个资产 id 取（可选，与 dsl/type 互斥）`:        `여러 자산 id로 조회(선택 사항, dsl/type과 함께 사용 불가)`,
	`相关资产 id（可选，0/1/多个）：该事实涉及哪些资产`:          `관련 자산 id(선택 사항, 0/1/여러 개): 이 사실이 관련된 자산`,
	`相对路径(可选，默认 SKILL.md，如 scripts/run.py)`: `상대 경로(선택 사항, 기본 SKILL.md, 예: scripts/run.py)`,
	`真实流量 ID`: `실제 트래픽 ID`,
	`端口号`:     `포트 번호`,
	`端口号（service 非 HTTP 时必填）`:      `포트 번호(비HTTP service 필수)`,
	`绑定的 agent key(可选)`:            `연결할 agent key(선택 사항)`,
	`给 worker 的纠偏指令，明确让它停止什么、转向什么`: `worker 방향 수정 지시: 중단할 내용과 전환할 방향을 명확히 설명`,
	`要修改的 MCP 服务器 id`:              `수정할 MCP 서버 id`,
	`要修改的自定义工具 key`:                `수정할 사용자 정의 도구 key`,
	`要删除的 host：域名/子域名/IP。完全匹配，如 example.com 或 a.example.com 或 1.2.3.4`:       `삭제할 host: 도메인/하위 도메인/IP. 정확히 일치하는 값, 예: example.com 또는 a.example.com 또는 1.2.3.4`,
	`要取完整内容的 step_id（来自①/②返回；一次最多取 5 个，多传只返回前 5 个，其余在 omitted_step_ids 里列出）`: `전체 내용을 읽을 step_id(①/② 결과에서 확인. 한 번에 최대 5개, 초과 시 처음 5개만 반환하고 나머지는 omitted_step_ids에 표시)`,
	`要暂停的任务 id`:             `일시 중지할 작업 id`,
	`要纠偏的意图 id（= work 句柄）`:  `방향을 수정할 실행 계획 id(= work 핸들)`,
	`要终止的意图 id（= work 句柄）`:  `종료할 실행 계획 id(= work 핸들)`,
	`证据/PoC 文本`:             `증거/PoC 텍스트`,
	`证明它的发现/事实节点 id`:        `목표를 입증하는 발견/사실 노드 id`,
	`该 IP 绑定的域名列表（ip 类型可选）`: `이 IP에 연결된 도메인 목록(ip 유형 선택 사항)`,
	`该流量如何支持漏洞结论`:           `이 트래픽이 취약점 결론을 뒷받침하는 방식`,
	`该流量支持什么结论`:             `이 트래픽이 뒷받침하는 결론`,
	`详细报告全文,Markdown 格式`:    `상세 보고서 전체 내용, Markdown 형식`,
	`请求参数列表，每条含 location(query/body/header/path)/name/value/type（可选，追加不覆盖）`: `요청 매개변수 목록, 각 항목에 location(query/body/header/path)/name/value/type 포함(선택 사항, 덮어쓰지 않고 추가)`,
	`资产数组，每个元素对应一条资产记录`:                                                     `자산 배열, 각 요소는 자산 기록 하나에 대응`,
	`资产类型`: `자산 유형`,
	`资产类型过滤（可选）：root_domain/subdomain/service/app/endpoint/ip`:                                  `자산 유형 필터(선택 사항): root_domain/subdomain/service/app/endpoint/ip`,
	`资产类型过滤：root_domain|ip|subdomain|app|service|endpoint（独立字段，可与 dsl 叠加；单独 type 不足以查询，仍需 dsl）`: `자산 유형 필터: root_domain|ip|subdomain|app|service|endpoint(독립 필드, dsl과 함께 사용 가능. type만으로는 검색할 수 없으며 dsl 필요)`,
	`资产范围，一行一条：域名 / URL / IP / CIDR / ICP备案 / 企业关键词`:                                            `자산 범위, 줄마다 하나: 도메인 / URL / IP / CIDR / ICP 등록 정보 / 기업 키워드`,
	`起始字节偏移，默认 0`: `시작 바이트 오프셋, 기본 0`,
	`达成理由（必须是目标真正达成的证据，不能是“本轮无新方向”这类结束本轮的理由）`: `달성 근거(목표의 실제 달성 증거가 필요하며, 새로운 방향이 없다는 등의 회차 종료 사유는 사용할 수 없음)`,
	`返回上限，默认 100（可选）`:                `반환 한도, 기본 100(선택 사항)`,
	`返回上限，默认 10（可选）`:                 `반환 한도, 기본 10(선택 사항)`,
	`返回条数，默认 20，上限 100`:              `반환 개수, 기본 20, 최대 100`,
	`锚定的资产 id（可选，0/1/多个）`:            `연결할 자산 id(선택 사항, 0/1/여러 개)`,
	`锚定的资产 id（可选，0/1/多个；该任务内的资产 id）`: `연결할 자산 id(선택 사항, 0/1/여러 개, 해당 작업의 자산 id)`,
	`页码，从 0 开始，默认 0（按 ts 倒序分页）`:      `페이지 번호, 0부터 시작, 기본 0(ts 역순 페이지 나누기)`,
	`页码，从 1 起（默认 1）`:                 `페이지 번호, 1부터 시작(기본 1)`,
	`页面 <title> 内容（可选）`:              `페이지 <title> 내용(선택 사항)`,
}
